# Dataset paths configuration
raw_data_dir: data/raw
processed_data_dir: data/processed
root_data_dir: data

# MegaVul dataset configuration
megavul:
  dataset_path: data/preprocessed/megavul/c_cpp/dataset.json
  processed_path: data/processed/megavul/

# DiverseVul dataset configuration
diversevul:
  dataset_path: data/preprocessed/diversevul/diversevul.json
  metadata_path: data/preprocessed/diversevul/metadata.json
  processed_path: data/processed/diversevul/
